name: 'my_new_project'  # Nom de votre projet
version: '1.0.0'  # Version de votre projet
config-version: 2  # Version de configuration

# Profile de connexion pour dbt
profile: 'default'  # Vous pouvez spécifier un autre profil si nécessaire

# Emplacement des fichiers de modèle et autres fichiers
model-paths: ["models"]  # Chemin vers les modèles
analysis-paths: ["analyses"]  # Chemin vers les analyses
test-paths: ["tests"]  # Chemin vers les tests
seed-paths: ["seeds"]  # Chemin vers les fichiers de semence
macro-paths: ["macros"]  # Chemin vers les macros
snapshot-paths: ["snapshots"]  # Chemin vers les snapshots

# Répertoires pour les fichiers compilés et de nettoyage
target-path: "target"  # Répertoire des fichiers SQL compilés
clean-targets:
  - "target"
  - "dbt_packages"

# Configuration des modèles (materialisation, schémas, etc.)
models:
  my_new_project:
    # Configurations par défaut pour le répertoire example
    example:
      materialized: view  # Tous les modèles sous models/example seront matérialisés en tant que vues

    # Configuration pour le répertoire circle_parcel
    circle_parcel:
      staging:
       +materialized: view # Tous les modèles sous models/circle_parcel seront matérialisés en tant que tables
      intermediate:
       +materialized: view
      mart:
       +materialized: table
      schema: 'circle_schema'  # Schéma spécifique pour ces modèles (si nécessaire)
    
    # Si vous avez d'autres répertoires avec des configurations spécifiques, vous pouvez les ajouter ici
    greenweez:
      staging:
       +materialized: view # Tous les modèles sous models/circle_parcel seront matérialisés en tant que tables
      intermediate:
       +materialized: view
      mart:
       +materialized: table 
      schema: 'greenweez_schema'  # Schéma pour les modèles dans ce répertoire

