version: 2


sources:
  - name: raw #endroit où renommer le nom du data set
    schema: gz_raw_data #où se situe la table dans Big Query
    description: greenweez raw data sources
    tables:


        - name: sales
          identifier: raw_gz_sales #quel est le nom exacte de la table dans Big Query
          description: sales of greenweez / we have one per product_id found in each order_id
          columns:
            - name: "(orders_id || '_' || pdt_id)"
              description: primary key of the table
              tests:
                - unique
                - not_null


        - name: product
          identifier: raw_gz_product #quel est le nom exacte de la table dans Big Query
          description: purchase_price by products_id
          columns:
            - name: products_id
              description: primary key of the table
              tests:
                - unique
                - not_null

        - name: ship
          identifier: raw_gz_ship #quel est le nom exacte de la table dans Big Query
          description: shipcost and logcost by orders_id
          columns:
              - name: orders_id
                description: primary key of the table
                tests:
                  - unique
                  - not_null